name: Build and Package JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      # Step 3: Cache SBT dependencies
      - name: Cache SBT dependencies
        uses: coursier/cache-action@v6

      # Step 4: Build bundled JAR
      - name: Build with SBT
        run: sbt assembly

      # Step 5: Upload the artifact
      - name: Upload JAR to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SampleUBAM
          path: target/scala-3.3/*.jar