name: Build and Package JAR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Java
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin

      # Step 3: Install SBT
      - name: Install SBT
        run: |
          echo "Installing SBT from direct binary download"
          
          # Download and extract the latest SBT tarball
          curl -Ls https://github.com/sbt/sbt/releases/download/v1.9.7/sbt-1.9.7.tgz | tar xz
          
          # Move extracted SBT files to /usr/local/sbt
          sudo mv sbt /usr/local/sbt
          
          # Create a symlink in /usr/local/bin (which is in $PATH)
          sudo ln -s /usr/local/sbt/bin/sbt /usr/local/bin/sbt
          
          echo "SBT installed successfully and added to PATH"
          
          # Confirm sbt is available and installed
          sbt --version

      # Step 4: Cache SBT dependencies
      - name: Cache SBT dependencies
        uses: coursier/cache-action@v6

      # Step 5: Build bundled JAR
      - name: Build with SBT
        run: sbt assembly

      # Step 6: Upload the artifact
      - name: Upload JAR to GitHub Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: SampleUBAM
          path: target/scala-3.3.4/*.jar